[workspace]
members = [
    "signals-relay-core",
    "processor",
]

resolver = "2"

[workspace.package]
version = "0.1.0-beta.2"
edition = "2021"
authors = ["Alessandro Bologna <alessandro.bologna@gmail.com>"]
license = "MIT"
rust-version = "1.91"
homepage = "https://github.com/dev7a/signals-relay"
repository = "https://github.com/dev7a/signals-relay"

[workspace.dependencies]
lambda-otel-lite = "0.19.0"
serverless-otlp-forwarder-core = "0.2.0"

tokio = { version = "1.50.0", features = ["full"] }
async-trait = "0.1.89"
tracing = { version = "0.1", features = ["log"] }
opentelemetry = { version = "0.31.0", features = ["trace"] }
opentelemetry-otlp = { version = "0.31.1", features = ["gzip-http"] }
opentelemetry-proto = { version = "0.31.0", features = ["gen-tonic", "trace"] }
tracing-opentelemetry = "0.32.1"
reqwest-tracing = { version = "0.7.0", features = ["opentelemetry_0_31"] }

aws-config = { version = "1.8.15", features = ["behavior-version-latest"] }
aws-sdk-kinesis = "1.103.0"
aws-sdk-secretsmanager = "1.103.0"
aws-sdk-sqs = "1.97.0"
lambda_runtime = { version = "1.1.2", features = ["anyhow", "tracing", "opentelemetry"] }
aws_lambda_events = { version = "1.1.2", default-features = false }

reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls"] }
reqwest-middleware = "0.5.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
prost = "0.14.3"

anyhow = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
