[package]
name = "signals-relay"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
signals-relay-core = { path = "../signals-relay-core" }
serverless-otlp-forwarder-core = { workspace = true, features = ["instrumented-client"] }
tokio.workspace = true
anyhow.workspace = true
async-trait.workspace = true
lambda_runtime.workspace = true
reqwest.workspace = true
tracing.workspace = true
lambda-otel-lite.workspace = true
opentelemetry-otlp.workspace = true
aws-config.workspace = true
aws-sdk-kinesis.workspace = true
aws-sdk-secretsmanager.workspace = true
aws-sdk-sqs.workspace = true
serde_json.workspace = true
aws_lambda_events = { workspace = true, features = ["cloudwatch_logs", "kinesis"] }
opentelemetry.workspace = true
serde = { workspace = true, features = ["derive"] }
opentelemetry-proto.workspace = true
prost.workspace = true
reqwest-middleware.workspace = true
reqwest-tracing.workspace = true
tracing-opentelemetry.workspace = true

[[bin]]
name = "span_processor_partitioner"
path = "src/bin/partitioner.rs"

[[bin]]
name = "span_processor_relay"
path = "src/bin/relay.rs"
